---
name: Create release
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.brand_name}}-${{ inputs.stream_name }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  create-runner:
    name: Create Hetzner Cloud runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.create-hcloud-runner.outputs.label }}
      server_id: ${{ steps.create-hcloud-runner.outputs.server_id }}
    steps:
      - name: Create runner
        id: create-hcloud-runner
        uses: Cyclenerd/hcloud-github-runner@v1
        with:
          mode: create
          github_token: ${{ secrets.AEMEATH_GH_PAT }}
          hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          server_type: ccx33
          location: hel1
          image: fedora-43 # Rocky Linux 9
  create-release:
    name: Create release
    runs-on: ${{ needs.create-runner.outputs.label }} # run the job on the newly created runner
    needs:
      - create-runner
    env:
      BUILD_CONTAINER: aemeath-build
      RUN_CMD: toolbox run -c aemeath
      HOME: /home/aemeath
      SHELL: /bin/bash
    steps:
      - name: Make home dir
        run: mkdir -p $HOME
      - name: Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:github-actions
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
      - uses: taiki-e/install-action@v2
        with:
          tool: git-cliff,just
      - name: Install podman and toolbx
        run: |
          sudo dnf -y install toolbox yq rclone
      - name: Generate tag
        run: |
          previous_version=$(git describe --tags $(git rev-list --tags --max-count=1))
          previous_date="${previous_version%%.*}"
          previous_rev="${previous_version#*.}"
          current_date=$(date +%Y%m%d)
          current_rev=1
          if [[ "$previous_date" == "$current_date" ]]; then
            current_rev=$((previous_rev+1))
          fi
          echo "Previous Version: ${previous_date}.${previous_rev}"
          echo "Current Version: ${current_date}.${current_rev}"
          echo "image_version=${current_date}.${current_rev}" >> $GITHUB_ENV
        shell: bash
      - name: Configure tools
        run: |
          set -euox pipefail

          mkdir -p $HOME/.config
          ./.github/scripts/buildstream-conf.sh > $HOME/.config/buildstream.conf
          mkdir -p $HOME/.config/rclone
          ./.github/scripts/rclone-conf.sh > $HOME/.config/rclone/rclone.conf
        shell: bash
        env:
          S3_ACCESS_KEY_ID: ${{secrets.S3_ACCESS_KEY_ID}}
          S3_SECRET_ACCESS_KEY: ${{secrets.S3_SECRET_ACCESS_KEY}}
      - name: Set up environment
        run: |
          echo "$AEMEATH_CRT" > aemeath.crt
          echo "$AEMEATH_KEY" > aemeath.key

          echo "image-version: ${{  env.image_version }}" > include/image-version.yml
        shell: bash
        env:
          AEMEATH_CRT: ${{secrets.BST_ARTIFACT_PUSH_CERT}}
          AEMEATH_KEY: ${{secrets.BST_ARTIFACT_PUSH_KEY}}
      - name: Set up keys
        run: |
          echo "$DB_CRT" > files/boot-keys/DB.crt
          echo "$DB_KEY" > files/boot-keys/DB.key
          echo "$KEK_CRT" > files/boot-keys/KEK.crt
          echo "$KEK_KEY" > files/boot-keys/KEK.key
          echo "$MODULE_CRT" > files/boot-keys/linux-module-cert.crt
          echo "$MODULE_KEY" > files/boot-keys/linux-module-cert.key
          echo "$PK_CRT" > files/boot-keys/PK.crt
          echo "$PK_KEY" > files/boot-keys/PK.key
          echo "$VENDOR_CRT" > files/boot-keys/VENDOR.crt
          echo "$VENDOR_KEY" > files/boot-keys/VENDOR.key
          mkdir -p files/boot-keys/modules
          cp files/boot-keys/linux-module-cert.crt files/boot-keys/modules
        shell: bash
        env:
          DB_CRT: ${{secrets.DB_CRT}}
          DB_KEY: ${{secrets.DB_KEY}}
          KEK_CRT: ${{secrets.KEK_CRT}}
          KEK_KEY: ${{secrets.KEK_KEY}}
          MODULE_CRT: ${{secrets.MODULE_CRT}}
          MODULE_KEY: ${{secrets.MODULE_KEY}}
          PK_CRT: ${{secrets.PK_CRT}}
          PK_KEY: ${{secrets.PK_KEY}}
          VENDOR_CRT: ${{secrets.VENDOR_CRT}}
          VENDOR_KEY: ${{secrets.VENDOR_KEY}}
      - name: Download Microsoft keys
        run: $HOME/.install-action/bin/just microsoft-keys
      - name: Prepare container
        run: |
          toolbox_image=registry.gitlab.com/freedesktop-sdk/infrastructure/freedesktop-sdk-docker-images/bst2:4387d0fa82f12808377dacc5feaf08a0d82a06af
          podman pull $toolbox_image
          toolbox create -i $toolbox_image aemeath
          # Sanity check
          $RUN_CMD ls
        shell: bash
      - name: Build components
        run: |
          $RUN_CMD $HOME/.install-action/bin/just build
        shell: bash
      - name: Disable push for building images
        run: |
          ./.github/scripts/buildstream-conf.sh nopush > $HOME/.config/buildstream.conf
        shell: bash
      - name: Build usr and kernel images
        run: |
          $RUN_CMD $HOME/.install-action/bin/just export
        shell: bash
      - name: Build disk images
        run: |
          $RUN_CMD $HOME/.install-action/bin/just disk-image
        shell: bash
      - name: Build live image
        run: |
          $RUN_CMD $HOME/.install-action/bin/just live-image
        shell: bash
      - name: Copy artifacts to S3 bucket
        run: |
          set -euox pipefail

          for f in target/*
          do
            rclone copy "$f" fina:aemeath/sysupdate/
          done
          for f in disks/*
          do
            rclone copy "$f" fina:aemeath/images/
          done
          for f in live/*
          do
            rclone copy "$f" fina:aemeath/images/
          done
        shell: bash
      - name: Import component versions
        run: |
          yq -o=shell include/versions.yml >> ${GITHUB_ENV}
      - name: Generate Notes
        run: |
          cat > "CHANGELOG.md" << EOF
          # Aemeath OS ${{ env.image_version }}
          ## Components
          |**Package**            |**Version**               |
          |-----------------------|--------------------------|
          |**Freedesktop SDK**    |${{ env.sdk_version }}    |
          |**Qt**                 |${{ env.qt6_version }}    |
          |**KDE Frameworks**     |${{ env.kf6_version }}    |
          |**KDE Plasma**         |${{ env.plasma_version }} |
          |**KDE Gear**           |${{ env.gear_version }}   |

          ## Downloads
          * [Disk Image](https://aemeath.fuxuan.nanao.moe/images/aemeath_${{ env.image_version }}.img.zst)
          * [Live Image](https://aemeath.fuxuan.nanao.moe/images/aemeath-live_${{ env.image_version }}.img.zst)

          **NOTE: due to space limitations, only recent versions are downloadable**

          EOF
          git cliff --unreleased --tag "${{ env.image_version }}" --strip header >> CHANGELOG.md
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
      - name: Create tag
        run: |
          git tag "${{ env.image_version }}"
          git push origin tag "${{ env.image_version }}"
        shell: bash
      - name: Create Release
        uses: softprops/action-gh-release@v2 # v2
        with:
          name: "Aemeath OS ${{ env.image_version }}"
          tag_name: ${{ env.image_version }}
          body_path: CHANGELOG.md
          make_latest: true
  delete-runner:
    name: Delete Hetzner Cloud runner
    needs:
      - create-runner # required to get output from the create-runner job
      - create-release # required to wait when the main job is done
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Delete runner
        uses: Cyclenerd/hcloud-github-runner@v1
        with:
          mode: delete
          github_token: ${{ secrets.AEMEATH_GH_PAT }}
          hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          name: ${{ needs.create-runner.outputs.label }}
          server_id: ${{ needs.create-runner.outputs.server_id }}